name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "30 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update readme
        uses: athul/waka-readme@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
